// frontend/src/components/layout/Header.tsx
import {
  SignedIn,
  SignedOut,
  SignInButton,
  UserButton,
} from '@clerk/clerk-react';

export default function Header() {
  return (
    <header className="sticky top-0 z-50 bg-black text-white">
      <div className="polaris-container flex items-center justify-between">
        <h1>Header</h1>
        <SignedOut>
          <SignInButton />
        </SignedOut>
        <SignedIn>
          <UserButton />
        </SignedIn>
      </div>
    </header>
  );
}

// frontend/src/components/layout/Header.vue
<script setup lang="ts">
import { SignedIn, SignedOut, SignInButton, UserButton } from '@clerk/vue'
import Container from './Container.vue'
</script>

<template>
  <header class="sticky top-0 z-50 bg-black text-white">
    <Container>
      <div class="flex items-center justify-between">
        <p>This is the header</p>
        <div>
          <SignedOut>
            <SignInButton />
          </SignedOut>
          <SignedIn>
            <UserButton />
          </SignedIn>
        </div>
      </div>
    </Container>
  </header>
</template>
