// frontend/src/components/layout/Layout.tsx
import Container from './Container';
import Footer from './Footer';
import Header from './Header';
import { Outlet } from 'react-router';

export default function Layout() {
  return (
    <div className="bg-background min-h-svh">
      <Header />
      <Container>
        <main className="flex min-h-svh flex-col items-center justify-center">
          <Outlet />
        </main>
      </Container>
      <Footer />
    </div>
  );
}

// frontend/src/components/layout/Layout.vue
<script setup lang="ts">
import Header from './Header.vue'
import Footer from './Footer.vue'
import Container from './Container.vue'
</script>

<template>
  <div class="bg-background min-h-svh">
    <Header />
    <Container>
      <main class="flex min-h-svh flex-col items-center justify-center">
        <slot />
      </main>
    </Container>
    <Footer />
  </div>
</template>
